# Basis types (copied from C++ data_spec.hpp)
BASIS_TYPE_SH = 1
BASIS_TYPE_3D_TEXTURE = 4
BASIS_TYPE_MLP = 255

# for surface type
SURFACE_TYPE_NONE = 100
SURFACE_TYPE_PLANE = 101
SURFACE_TYPE_SDF = 102
SURFACE_TYPE_UDF = 103
SURFACE_TYPE_UDF_ALPHA = 104
